In [1]:
import pandas as pd
from scipy.stats import ks_2samp, wasserstein_distance

real = pd.read_csv('data/synthetic/baseline_auto.csv')
ctgan = pd.read_csv('data/synthetic/ctgan_auto_50k.csv')
tvae = pd.read_csv('data/synthetic/tvae_auto_50k.csv')

In [2]:
print("Real rows:", len(real))
print("CTGAN rows:", len(ctgan))
print("TVAE rows:", len(tvae))

Real rows: 10000
CTGAN rows: 50000
TVAE rows: 50000

In [3]:
for col in ['premium', 'claim_amount']:

    print("\nColumn:", col)

    ks_ctgan = ks_2samp(real[col], ctgan[col])
    ks_tvae = ks_2samp(real[col], tvae[col])

    wd_ctgan = wasserstein_distance(real[col], ctgan[col])
    wd_tvae = wasserstein_distance(real[col], tvae[col])

    print("CTGAN KS p-value:", ks_ctgan.pvalue)
    print("TVAE KS p-value:", ks_tvae.pvalue)

    print("CTGAN Wasserstein:", wd_ctgan)
    print("TVAE Wasserstein:", wd_tvae)

Column: premium
CTGAN KS p-value: 6.793534425206146e-69
TVAE KS p-value: 2.111289207595162e-155
CTGAN Wasserstein: 2541.0125921999984
TVAE Wasserstein: 4460.611382199998

Column: claim_amount
CTGAN KS p-value: 1.2459402753020215e-20
TVAE KS p-value: 1.8033047947941732e-306
CTGAN Wasserstein: 905.2801841999972
TVAE Wasserstein: 3007.436276999997

In [4]:
ctgan[['premium', 'claim_amount']].describe()

             premium   claim_amount
count   50000.000000   50000.000000
mean    22415.566918   11703.605181
std     12324.434958   10172.259463
min      3098.890000     370.520000
25%     14110.850000    4644.322500
50%     19648.470000    8320.415000
75%     27443.785000   16170.037500
max    122345.300000  117808.630000

In [5]:
tvae[['premium', 'claim_amount']].describe()

            premium  claim_amount
count  50000.000000  50000.000000
mean   20497.587101  12842.173573
std     7823.225993   7265.365241
min     3098.890000    370.520000
25%    14132.452500   7459.037500
50%    19927.005000  11489.845000
75%    26166.650000  16687.302500
max    76827.410000  59357.490000